export const myTechnologies = [
    { label: "Next.js", svg: "/skills/nextjs.svg", description: "A React framework for production.", genre: "Frontend" },
    { label: "React.js", svg: "/skills/reactjs.svg", description: "A JavaScript library for building user interfaces.", genre: "Frontend" },
    { label: "Angular", svg: "/skills/angular.svg", description: "A platform for building mobile and desktop web applications.", genre: "Frontend" },
    { label: "Redux", svg: "/skills/redux.svg", description: "A Predictable State Container for JS Apps.", genre: "Frontend" },
    { label: "JavaScript", svg: "/skills/js.svg", description: "A high-level, just-in-time compiled, object-oriented programming language.", genre: "Frontend" },
    { label: ".NET CORE", svg: "/skills/dotnet.svg", description: "A cross-platform, high-performance framework for building modern, cloud-based, Internet-connected applications.", genre: "Backend" },
    { label: "C#", svg: "/skills/cSharp.svg", description: "A modern, object-oriented programming language developed by Microsoft.", genre: "Backend" },
    { label: "MySQL", svg: "/skills/mysql.svg", description: "An open-source relational database management system.", genre: "Database" },
    { label: "HTML", svg: "/skills/html.svg", description: "The standard markup language for documents designed to be displayed in a web browser.", genre: "Frontend" },
    { label: "CSS", svg: "/skills/css.svg", description: "A style sheet language used for describing the presentation of a document written in a markup language.", genre: "Frontend" },
    { label: "Sass", svg: "/skills/sass.svg", description: "A preprocessor scripting language that is interpreted or compiled into CSS.", genre: "Frontend" },
    { label: "Tailwind", svg: "/skills/tailwind.svg", description: "A utility-first CSS framework for rapid UI development.", genre: "Frontend" },
    { label: "Material UI", svg: "/skills/materialui.svg", description: "A popular React UI framework.", genre: "Frontend" },
    { label: "Bootstrap", svg: "/skills/bootstrap.svg", description: "The most popular HTML, CSS, and JS library in the world.", genre: "Frontend" },
    // { label: "Aws", svg: "/skills/aws.svg", description: "Amazon Web Services offers reliable, scalable, and inexpensive cloud computing services.", genre: "Cloud" },
    { label: "VS Code", svg: "/skills/vscode.svg", description: "A source-code editor made by Microsoft for Windows, Linux, and macOS.", genre: "Tools" },
    { label: "Github", svg: "/skills/github.svg", description: "A provider of Internet hosting for software development and version control using Git.", genre: "Tools" },
];
