export const myTechnologies = [
    { label: "Next.js", svg: "/technologies/nextjs-icon-svgrepo-com-ed.svg", description: "A React framework for production.", genre: "Frontend" },
    { label: "React.js", svg: "/technologies/react-javascript-js-framework-facebook-svgrepo-com.svg", description: "A JavaScript library for building user interfaces.", genre: "Frontend" },
    { label: "Redux", svg: "/technologies/redux-svgrepo-com.svg", description: "A Predictable State Container for JS Apps.", genre: "Frontend" },
    { label: "Angular", svg: "/technologies/angular-svgrepo-com.svg", description: "A platform for building mobile and desktop web applications.", genre: "Frontend" },
    { label: "TypeScript", svg: "/technologies/typescript-svgrepo-com.svg", description: "A high-level, just-in-time compiled, object-oriented programming language.", genre: "Frontend" },
    { label: "JavaScript", svg: "/technologies/javascript-svgrepo-com.svg", description: "A high-level, just-in-time compiled, object-oriented programming language.", genre: "Frontend" },
    { label: ".NET CORE", svg: "/technologies/dotnet-svgrepo-com.svg", description: "A cross-platform, high-performance framework for building modern, cloud-based, Internet-connected applications.", genre: "Backend" },
    { label: "C#", svg: "/technologies/c-sharp-svgrepo-com.svg", description: "A modern, object-oriented programming language developed by Microsoft.", genre: "Backend" },
    { label: "MySQL", svg: "/technologies/mysql-svgrepo-com.svg", description: "An open-source relational database management system.", genre: "Database" },
    { label: "HTML5", svg: "/technologies/html-5-svgrepo-com.svg", description: "The standard markup language for documents designed to be displayed in a web browser.", genre: "Frontend" },
    { label: "CSS3", svg: "/technologies/css-3-svgrepo-com.svg", description: "A style sheet language used for describing the presentation of a document written in a markup language.", genre: "Frontend" },
    { label: "Sass", svg: "/technologies/sass-svgrepo-com.svg", description: "A preprocessor scripting language that is interpreted or compiled into CSS.", genre: "Frontend" },
    { label: "Tailwind", svg: "/technologies/tailwind-svgrepo-com.svg", description: "A utility-first CSS framework for rapid UI development.", genre: "Frontend" },
    { label: "Material UI", svg: "/technologies/material-ui-svgrepo-com.svg", description: "A popular React UI framework.", genre: "Frontend" },
    { label: "Bootstrap", svg: "/technologies/bootstrap-5-1.svg", description: "The most popular HTML, CSS, and JS library in the world.", genre: "Frontend" },
    // { label: "Aws", svg: "/technologies/aws.svg", description: "Amazon Web Services offers reliable, scalable, and inexpensive cloud computing services.", genre: "Cloud" },
    { label: "VS Code", svg: "/technologies/vs-code-svgrepo-com.svg", description: "A source-code editor made by Microsoft for Windows, Linux, and macOS.", genre: "Tools" },
    { label: "Github", svg: "/technologies/github-svgrepo-com.svg", description: "A provider of Internet hosting for software development and version control using Git.", genre: "Tools" },
];
